workflows:
  android-release:
    name: Android AAB

    environment:
      flutter: stable

      groups:
        - keystore

      android_signing:
        - keystore

    scripts:
      - flutter pub get
      - flutter build appbundle --release

    artifacts:
      - build/app/outputs/bundle/release/*.aab
